# Generated by Django 5.2.4 on 2025-07-26 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_alter_paciente_options_paciente_contacto_emergencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('medicina_general', 'Medicina General'), ('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('ginecologia', 'Ginecología'), ('pediatria', 'Pediatría'), ('ortopedia', 'Ortopedia'), ('neurologia', 'Neurología'), ('psiquiatria', 'Psiquiatría'), ('oftalmologia', 'Oftalmología'), ('otorrinolaringologia', 'Otorrinolaringología'), ('urologia', 'Urología'), ('gastroenterologia', 'Gastroenterología'), ('endocrinologia', 'Endocrinología'), ('nefrologia', 'Nefrología'), ('hematologia', 'Hematología'), ('oncologia', 'Oncología'), ('reumatologia', 'Reumatología'), ('neumologia', 'Neumología'), ('traumatologia', 'Traumatología'), ('cirugia_general', 'Cirugía General'), ('otro', 'Otra')], default='medicina_general', max_length=50)),
                ('numero_colegio', models.CharField(max_length=20, unique=True, verbose_name='Número de Colegio Médico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_consultorio', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia')], default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doctores/')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('capacitacion', 'Capacitación'), ('conferencia', 'Conferencia'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.doctor')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo_cita', models.CharField(choices=[('primera_vez', 'Primera Vez'), ('control', 'Control'), ('emergencia', 'Emergencia'), ('consulta', 'Consulta'), ('seguimiento', 'Seguimiento'), ('procedimiento', 'Procedimiento')], default='consulta', max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_show', 'No Show'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='agenda.doctor')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora_inicio'],
                'unique_together': {('doctor', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=10)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agenda.cita')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_cita', models.IntegerField(default=30, help_text='Duración en minutos', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(120)])),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.doctor')),
            ],
            options={
                'verbose_name': 'Horario de Doctor',
                'verbose_name_plural': 'Horarios de Doctores',
                'ordering': ['doctor', 'dia_semana', 'hora_inicio'],
                'unique_together': {('doctor', 'dia_semana')},
            },
        ),
    ]
