# Generated by Django 5.2.4 on 2025-07-26 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_apellido_remove_paciente_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='notificacion_email',
            new_name='notificar_correo',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='notificacion_sms',
            new_name='notificar_sms',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='notificacion_whatsapp',
            new_name='notificar_whatsapp',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_modificacion',
            new_name='ultima_modificacion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='documento_identidad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='zona_residencia',
        ),
        migrations.AddField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='documento_identificacion',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(default='Ciudad', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(default='paciente@ejemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(default='Sin dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='identidad_genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(default='Guatemalteca', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pais',
            field=models.CharField(default='Guatemala', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='primer_apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='primer_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('DPI', 'DPI'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='DPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_paciente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
