# Generated by Django 5.2.4 on 2025-07-26 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_notificacion_email_paciente_notificar_correo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unión libre', 'Unión libre'), ('Separado/a', 'Separado/a')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, choices=[('Cónyuge', 'Cónyuge'), ('Padre', 'Padre'), ('Madre', 'Madre'), ('Hijo/a', 'Hijo/a'), ('Hermano/a', 'Hermano/a'), ('Abuelo/a', 'Abuelo/a'), ('Tío/a', 'Tío/a'), ('Primo/a', 'Primo/a'), ('Amigo/a', 'Amigo/a'), ('Vecino/a', 'Vecino/a'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('No binario', 'No binario'), ('Prefiero no decir', 'Prefiero no decir')], default='Masculino', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('DPI', 'DPI - Documento Personal de Identificación'), ('Pasaporte', 'Pasaporte'), ('Carné de Extranjería', 'Carné de Extranjería'), ('Otro', 'Otro documento')], default='DPI', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['primer_nombre', 'primer_apellido'], name='pacientes_p_primer__f9c238_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['documento_identificacion'], name='pacientes_p_documen_94bb30_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['telefono'], name='pacientes_p_telefon_f5fa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['estado'], name='pacientes_p_estado_8c5b22_idx'),
        ),
    ]
