# Generated by Django 5.2.4 on 2025-07-26 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_options_consulta_altura_and_more'),
        ('pacientes', '0004_alter_paciente_options_paciente_contacto_emergencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_antecedente', models.CharField(choices=[('personal', 'Personal'), ('familiar', 'Familiar'), ('quirurgico', 'Quirúrgico'), ('alergico', 'Alérgico'), ('medicamento', 'Medicamento'), ('habito', 'Hábito'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('severidad', models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('severo', 'Severo'), ('crítico', 'Crítico')], max_length=20, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Antecedente Médico',
                'verbose_name_plural': 'Antecedentes Médicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evolucion', models.DateField()),
                ('tipo_evolucion', models.CharField(choices=[('mejoria', 'Mejoría'), ('estable', 'Estable'), ('empeoramiento', 'Empeoramiento'), ('complicacion', 'Complicación'), ('recuperacion', 'Recuperación'), ('cronico', 'Crónico')], max_length=20)),
                ('sintomas_actuales', models.TextField()),
                ('signos_vitales', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('diagnostico_actual', models.TextField()),
                ('plan_tratamiento', models.TextField()),
                ('medicamentos_actuales', models.TextField(blank=True, null=True)),
                ('dosis_medicamentos', models.TextField(blank=True, null=True)),
                ('efectos_secundarios', models.TextField(blank=True, null=True)),
                ('proxima_evaluacion', models.DateField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='pacientes.paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evolución Clínica',
                'verbose_name_plural': 'Evoluciones Clínicas',
                'ordering': ['-fecha_evolucion'],
            },
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('imagen', 'Imagenología'), ('cardiovascular', 'Cardiovascular'), ('neurologico', 'Neurológico'), ('respiratorio', 'Respiratorio'), ('gastrointestinal', 'Gastrointestinal'), ('endocrino', 'Endocrino'), ('ginecologico', 'Ginecológico'), ('urologico', 'Urológico'), ('dermatologico', 'Dermatológico'), ('oftalmologico', 'Oftalmológico'), ('otorrino', 'Otorrinolaringológico'), ('ortopedico', 'Ortopédico'), ('psicologico', 'Psicológico'), ('otro', 'Otro')], max_length=20)),
                ('nombre_examen', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('valores_normales', models.TextField(blank=True, null=True)),
                ('interpretacion', models.TextField(blank=True, null=True)),
                ('archivo_resultado', models.FileField(blank=True, null=True, upload_to='examenes/')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='solicitado', max_length=20)),
                ('laboratorio', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='pacientes.paciente')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medicamento', models.CharField(max_length=200)),
                ('principio_activo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_medicamento', models.CharField(choices=[('recetado', 'Recetado'), ('automedicacion', 'Automedicación'), ('suplemento', 'Suplemento'), ('vitamina', 'Vitamina'), ('otro', 'Otro')], default='recetado', max_length=20)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(choices=[('una_vez_dia', 'Una vez al día'), ('dos_veces_dia', 'Dos veces al día'), ('tres_veces_dia', 'Tres veces al día'), ('cuatro_veces_dia', 'Cuatro veces al día'), ('cada_8_horas', 'Cada 8 horas'), ('cada_12_horas', 'Cada 12 horas'), ('cada_24_horas', 'Cada 24 horas'), ('segun_necesidad', 'Según necesidad'), ('otro', 'Otro')], max_length=20)),
                ('duracion_tratamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('efectos_secundarios', models.TextField(blank=True, null=True)),
                ('alergia', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta_prescriptora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pacientes.paciente')),
                ('prescrito_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
