# Generated by Django 5.2.4 on 2025-07-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_antecedentemedico_evolucionclinica_examenmedico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_medicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='factor_rh',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
