# Generated by Django 5.2.4 on 2025-07-26 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_consulta_options_consulta_altura_and_more'),
        ('pacientes', '0005_antecedentemedico_evolucionclinica_examenmedico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receta', 'Receta Médica'), ('consulta', 'Resumen de Consulta'), ('recordatorio', 'Recordatorio de Cita'), ('resultado', 'Resultado de Examen'), ('emergencia', 'Alerta de Emergencia')], max_length=20)),
                ('telefono', models.CharField(help_text='Número de teléfono del paciente', max_length=20)),
                ('mensaje', models.TextField(help_text='Mensaje enviado por WhatsApp')),
                ('plantilla_usada', models.CharField(blank=True, help_text='Plantilla de WhatsApp utilizada', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='ID del mensaje en WhatsApp', max_length=100, null=True)),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si falló el envío', null=True)),
                ('intentos_envio', models.IntegerField(default=0, help_text='Número de intentos de envío')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='PDF o imagen adjunta', null=True, upload_to='whatsapp_archivos/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_whatsapp', to='consultas.consulta')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_whatsapp', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Notificación WhatsApp',
                'verbose_name_plural': 'Notificaciones WhatsApp',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['paciente', 'tipo'], name='consultas_n_pacient_3acd5f_idx'), models.Index(fields=['estado', 'fecha_envio'], name='consultas_n_estado_3b5f0d_idx'), models.Index(fields=['whatsapp_message_id'], name='consultas_n_whatsap_a311dd_idx')],
            },
        ),
    ]
